name: tobo_apk
description: "Aplikasi Tobo Interior"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter  
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8 
  gap: ^3.0.1
  http: ^1.6.0
  google_fonts: ^6.3.3
  url_launcher: ^6.2.6  
  flutter_svg: ^2.2.3
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_tobo.png"

